/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as CarteirinhaRouteImport } from './routes/carteirinha'
import { Route as ContratoRouteImport } from './routes/contrato'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PerfilRouteImport } from './routes/perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirinhaRoute = CarteirinhaRouteImport.update({
  id: '/carteirinha',
  path: '/carteirinha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoRoute = ContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/carteirinha': typeof CarteirinhaRoute
  '/contrato': typeof ContratoRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/carteirinha': typeof CarteirinhaRoute
  '/contrato': typeof ContratoRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beneficios': typeof BeneficiosRoute
  '/carteirinha': typeof CarteirinhaRoute
  '/contrato': typeof ContratoRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beneficios'
    | '/carteirinha'
    | '/contrato'
    | '/financeiro'
    | '/login'
    | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficios'
    | '/carteirinha'
    | '/contrato'
    | '/financeiro'
    | '/login'
    | '/perfil'
  id:
    | '__root__'
    | '/'
    | '/beneficios'
    | '/carteirinha'
    | '/contrato'
    | '/financeiro'
    | '/login'
    | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeneficiosRoute: typeof BeneficiosRoute
  CarteirinhaRoute: typeof CarteirinhaRoute
  ContratoRoute: typeof ContratoRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteirinha': {
      id: '/carteirinha'
      path: '/carteirinha'
      fullPath: '/carteirinha'
      preLoaderRoute: typeof CarteirinhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato': {
      id: '/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof ContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeneficiosRoute: BeneficiosRoute,
  CarteirinhaRoute: CarteirinhaRoute,
  ContratoRoute: ContratoRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
